can_send:
  ros__parameters:
    # CAN 设备端口
    port: "can0"

    # 发送频率 (Hz)
    send_frequency: 500

    # CAN ID（单帧发送，所有数据合并到一帧）
    id_scan: 0x190

    # topics
    cmd_vel_topic: "/cmd_vel"
    vw_topic: "/vw"
    scan_mod_type_topic: "/scan_mod_type"
    #NLJG_mode_type_topic: "/auto_shoot_type"
    #outpost_mode_type_topic: "/outpost_mode_type"
    #all_detect_topic: "/detector/armor_presence"
    #game_status_topic: "/rm_referee/game_status"
    target_yaw_topic: "/target_yaw"

    # 超时门控 (s)
    cmd_vel_timeout_s: 0.1
    vw_timeout_s: 0.1

can_receive:
  ros__parameters:
    port: "can0"
    can_id: 0x180
    yaw_topic: "/target/yaw"
    pitch_topic: "/target/pitch"
    distance_topic: "/target/distance"
    publish_rate_hz: 500.0

target_frame:
  ros__parameters:
    publish_rate_hz: 500.0
    map_frame: "map"
    base_frame: "base_link"
    target_frame: "target_frame"
    target_pose_topic: "/detected_target_pose"

vyaw_tf_yaw_controller:
  ros__parameters:
    target_yaw_topic: "/target_yaw"
    map_frame: "map"
    base_frame: "base_link"

    # Pose of NLJG in map frame
    #NLJG_pose_x: 10.44
    #NLJG_pose_y: 0.0

    # Pose of outpost in map frame
    #outpost_pose_x: 13.48
    #outpost_pose_y: 3.92

    publish_rate_hz: 30.0
