tf_odom_publisher:
  ros__parameters:
    # 发布频率 (Hz)
    publish_rate: 100.0
    
    # ===== C: base_link → livox_frame 变换参数 =====
    # 平移 (m)
    base_link_to_livox_x: 0.22
    base_link_to_livox_y: 0.0
    base_link_to_livox_z: 0.0
    
    # 旋转 角度制
    base_link_to_livox_roll: 0.0
    base_link_to_livox_pitch: 45.0
    base_link_to_livox_yaw: 0.0

tf_only_odom:
  ros__parameters:
    # 发布频率 (Hz)
    publish_rate: 100.0
    
    # 平移 (m)
    base_link_to_livox_x: 0.22
    base_link_to_livox_y: 0.0
    base_link_to_livox_z: 0.0
    
    # 旋转 角度制
    base_link_to_livox_roll: 0.0
    base_link_to_livox_pitch: 45.0
    base_link_to_livox_yaw: 0.0