uint32 KEY_W = 1
uint32 KEY_S = 2
uint32 KEY_A = 4
uint32 KEY_D = 8
uint32 KEY_SHIFT = 16
uint32 KEY_CTRL = 32
uint32 KEY_Q = 64
uint32 KEY_E = 128
uint32 KEY_R = 256
uint32 KEY_F = 512
uint32 KEY_G = 1024
uint32 KEY_Z = 2048
uint32 KEY_X = 4096
uint32 KEY_C = 8192
uint32 KEY_V = 16384
uint32 KEY_B = 32768

std_msgs/Header header
int32 mouse_x
int32 mouse_y
int32 mouse_z
bool left_button_down
bool right_button_down
uint32 keyboard_value
bool mid_button_down
