sentry_comm_node:
  ros__parameters:
    serial_port: "/dev/ttyACM0"
    baud_rate: 115200
    send_frequency: 500
    timeout: 1.0
    max_retries: 5
    retry_delay: 2.0

sentry_reciever_node:
  ros__parameters:
    serial_port: "/dev/ttyACM0"
    baud_rate: 115200