serial_comm_node:
  ros__parameters:
    cmd_vel_topic: "/cmd_vel"
    vw_topic: "/vw"
    scan_mod_type_topic: "/scan_mod_type"

serial_receive_node:
  ros__parameters:
    hurt_armor_topic: "/hurt_armor"
    hp_topic: "/hp"
    match_stage_topic: "/match_stage"
    remain_time_topic: "/remain_time"
    remain_17mm_topic: "/remain_17mm"
    robot_color_topic: "/robot_color"
